title: Whacky Labs
tagline: apps and games
description: Making apps and games
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whackylabs.com" # the base hostname & protocol for your site
paginate: 5
permalink: pretty

sass:
  sass_dir: _sass
  style: :compressed

markdown: kramdown

author:
  name: Sidharth Juyal
  url: https://twitter.com/chunkyguy
