title: whackylabs
description: Rants on iOS, algorithms and graphics programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whackylabs.com" # the base hostname & protocol for your site
twitter_username: chunkyguy
github_username:  chunkyguy
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - 'jekyll-seo-tag'
  - 'html-proofer'
  - 'rubocop'
  - 'w3c_validators'
