title: Whacky Labs
tagline: apps and games
description: Making apps and games
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whackylabs.com" # the base hostname & protocol for your site
paginate: 5
permalink: pretty

sass:
  sass_dir: _sass
  style: "compressed"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-compose
  - github-pages

author:
  name: Sidharth Juyal
  twitter: chunkyguy
  url: https://whackylabs.com

twitter:
  username: whackylabs
  card: summary
