title: Whacky Labs
tagline: on iOS, algorithms and graphics programming
description: Rants on iOS, algorithms and graphics programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whackylabs.com" # the base hostname & protocol for your site
paginate: 5
permalink: pretty

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Sidharth Juyal
  url: https://twitter.com/chunkyguy
